name: png_display
description: A pseudo-pixel-display that writes PNG files.
environment:
  sdk: ^2.0.0-alpha.97
dependencies:
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^2.0.0
