dependencies:
  font_clock:
    path: ../../toit-font-clock
  pictogrammers_icons:
    url: github.com/toitware/toit-icons-pictogrammers
    version: ^1.0.0
  pixel_display:
    path: ../../toit-pixel-display
  png_display:
    path: ..
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.1.0
  server:
    path: ../../toit/system/lib/server
