environment:
  sdk: ^2.0.0-alpha.121
dependencies:
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.5.1
  pictogrammers_icons:
    url: github.com/toitware/toit-icons-pictogrammers
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^2.3.0
  png_display:
    path: ..
  roboto:
    url: github.com/toitware/toit-font-google-100dpi-roboto
    version: ^1.1.0
