name: CI

on:
  push:
  release:
    types: [published]

env:
  TOIT_VERSION: v2.0.0-alpha.144

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Toit SDK
        uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ env.TOIT_VERSION }}

      # Fetch the dependencies. Different for each platform.
      - name: Install dependencies - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
          ninja --version
          cmake --version
      - name: Install dependencies - macOS
        if: runner.os == 'macOS'
        run: |
          brew install ninja
          ninja --version
          cmake --version
      - name: Install dependencies - Windows
        if: runner.os == 'Windows'
        run: |
          choco install ninja
          ninja --version
          cmake --version

      - uses: suisei-cn/actions-download-file@v1.4.0
        name: Download Toit
        with:
          url: ${{ env.TOIT_URL }}
          target: ${{ env.DOWNLOAD_DIR }}

      - name: Extract Toit
        shell: bash
        run: |
          cd "$DOWNLOAD_DIR"
          tar x -f *.tar.gz

      - name: Run cmake
        shell: bash
        run: |
          make rebuild-cmake
          cmake "-DTOIT_EXEC=$TOIT_EXEC" "-DTPKG_EXEC=$TPKG_EXEC" build

      - name: Install packages
        run: |
          make install-pkgs

      - name: Test
        run: |
          make test
